when@test:
    services:
        App\Application\Debt\Command\PayDebt\PayDebtHandlerEntryPoint:
            public: true
            autowire: true
            autoconfigure: true
        App\Application\Security\RuntimeActorContextProvider:
            public: true
            autowire: true
            autoconfigure: true

        App\Application\Order\Command\AddProductToDraft\AddProductToDraftHandler:
            public: true
            autowire: true
            autoconfigure: true

        App\Application\Order\Command\ChangeDraftItemQuantity\ChangeDraftItemQuantityHandler:
            public: true
            autowire: true
            autoconfigure: true

        App\Application\Order\Command\AttachCustomerToDraft\AttachCustomerToDraftHandler:
            public: true
            autowire: true
            autoconfigure: true

        App\Application\Order\Command\DetachCustomerFromDraft\DetachCustomerFromDraftHandler:
            public: true
            autowire: true
            autoconfigure: true

        App\Application\Order\Command\RemoveDraftItem\RemoveDraftItemHandler:
            public: true
            autowire: true
            autoconfigure: true

        App\Application\Order\Query\GetDraftOrder\GetDraftOrderHandler:
            public: true
            autowire: true
            autoconfigure: true

        # Checkout concurrency worker
        App\Application\Order\Command\Checkout\CheckoutHandlerEntryPoint:
            public: true
            autowire: true
            autoconfigure: true
