services:
    App\Application\Security\ActorContext:
        public: true
        arguments:
            $userId: 1
            $sessionId: null
            $requestId: 'test-checkout-golden-path'

    App\Application\Security\RuntimeActorContextProvider:
        public: true

    App\Application\Order\Command\Checkout\CheckoutHandlerEntryPoint:
        autowire: true
        autoconfigure: true
        public: true

#    App\Application\Product\Command\AdjustStock\AdjustStockHandler:
#        public: true
